exclude:
  - package.json
  - gulpfile.js
  - node_modules
  - server

# permalink: /:name/
permalink: pretty
# START sectipn for pageGenerator | For more info folow -> https://github.com/avillafiorita/jekyll-datapage_gen
page_gen-dirs: true # uncomment, if you prefer to generate named folders

# Services parts
page_gen:
  - index_files: false
    data: "services-pages.services_page_content"
    template: "service"
    name: "title"
    dir: "services"

  - index_files: false
    data: services-pages.mobile_aplication
    template: "service"
    name: "title"
    dir: "services"

  - index_files: false
    data: services-pages.vr_ar_and_mr_apps
    template: "service"
    name: "title"
    dir: "services"

  - index_files: false
    data: services-pages.software_testing
    template: "service"
    name: "title"
    dir: "services"

  - index_files: false
    data: services-pages.database_designe
    template: "service"
    name: "title"
    dir: "services"

  - index_files: false
    data: services-pages.remote_developers
    template: "service"
    name: "title"
    dir: "services"

  # technologies parts

  - index_files: false
    data: technologies-pages.mobile
    template: "service"
    name: "title"
    dir: "technologies"

  - index_files: false
    data: technologies-pages.back_end
    template: "service"
    name: "title"
    dir: "technologies"

  - index_files: false
    data: technologies-pages.front_end
    template: "service"
    name: "title"
    dir: "technologies"

  # Example to use filter for create page
  # - data: "books"
  #   template: "book"
  #   name: "title"
  #   dir: "books-i-have-read"
  #   filter: read # read is a boolean value in the YML file

  # read is a boolean value in the YML file, but I need to test for
  # falsity (read: false). The field `filter` is no good and I need to
  # use filter_conditions

  # END sectipn for pageGenerator